namespace Myria.Wpf.Services
{
    public enum NavigationFrameType
    {
        Main = 0,
        Startup = 1,
        Settings = 2,
        CharacterMenu = 3,
        Game = 4,
        IngameMenu = 5,
        IngameSettings = 6,
        NpcWindow = 7,
        SkillDetailWindow = 8,
        AddFriendWindow = 9,
        TradeWindow = 10,
        MultiplayerHub = 11,
    }

    public enum Nav
    {
        Startup = 0,
        Main = 1,
        Login = 2,
        Register = 3,
        Settings = 4,
        SettingsVisuals = 5,
        SettingsKeybindings = 6,
        CharacterSelection = 7,
        CharacterCreation = 8,
        RaceSelection = 9,
        Game = 10,
        Room = 11,
        Combat = 12,
        Character = 13,
        Quest = 14,
        Friends = 15,
        Inventory = 16,
        Map = 17,
        Skills = 18,
        Job = 19,
        GeneralNpcPanel = 21,
        ClassPanel = 22,
        CraftPanel = 23,
        DialogPanel = 24,
        JobMasterPanel = 25,
        QuestDialogPanel = 26,
        ShopPanel = 27,
        UpgradePanel = 28,
        Trade = 29,
        Shop = 30,
        AddFriend = 31,
        SkillCombination = 32,
        SkillSlot = 33,
        EquipmentPanel = 34,
        InventoryPanel = 35,
        MoneyPanel = 36,
        SettingsLanguage = 37,
        Runes = 38,
        RuneDrawing = 39,
        RuneLexica = 40,
        Guild = 41,
        SettingsMods = 42,
    }
}
